// Copyright 2018 Sourcerer Inc. All Rights Reserved.
// Author: Alexander Surkov (alex@sourcerer.io)

package test.tests.extractors

/**
 * A list of all file names whose language recognition needs to be checked
 * or fixed.
 */
var ignoredSamplesWildcards = listOf(
    "*/1C Enterprise/*",
    "*/ABAP/*",
    "*/AppleScript/*",
    "*/Apex/*",
    "*/APL/*",
    "*/API Blueprint/*",
    "*/Alloy/*",
    "*/Apollo Guidance Computer/*",
    "*/ASN.1/*",
    "*/Awk/*",
    "*/Ant Build System/*",
    "*/Assembly/*.inc",
    "*/Assembly/*.a51",
    "*/Assembly/*.nasm",
    "*/Alpine Abuild/*",
    "*/AspectJ/*",
    "*/AMPL/*",
    "*/AutoHotkey/*",
    "*/AsciiDoc/*",
    "*/Agda/*",
    "*/ATS/*",
    "*/ApacheConf/*",
    "*/ActionScript/*",
    "*/AGS Script/*",
    "*/Adobe Font Metrics/*",
    "*/Brightscript/*",
    "*/Bluespec/*",
    "*/Blade/*",
    "*/Brainfuck/*",
    "*/BlitzBasic/*",
    "*/BitBake/*",
    "*/Ballerina/*",
    "*/BlitzMax/*",
    "*/C/*.h",
    "*/C/script",
    "*/C/*.cats",
    "*/C/*.H",
    "*/C#/*.cs",
    "*/C++/*.inc",
    "*/C++/*.re",
    "*/C++/*.ino",
    "*/C++/*.ipp",
    "*/CartoCSS/*.mss",
    "*/CLIPS/*",
    "*/CMake/*",
    "*/COBOL/*.ccp",
    "*/CSON/*",
    "*/CSV/*",
    "*/CWeb/*",
    "*/CartoCSS/*",
    "*/Ceylon/*",
    "*/Chapel/*",
    "*/Charity/*",
    "*/Cirru/*",
    "*/Clarion/*",
    "*/Clean/*",
    "*/Click/*",
    "*/Clojure/*.hic",
    "*/Clojure/*.boot",
    "*/Clojure/*.cljx",
    "*/Clojure/*.hl",
    "*/Clojure/*.cljscm",
    "*/Clojure/*.cl2",
    "*/Closure Templates/*",
    "*/CoNLL-U/*",
    "*/CoffeeScript/*.cake",
    "*/CoffeeScript/*.cjsx",
    "*/ColdFusion/*",
    "*/ColdFusion CFC/*",
    "*/Common Lisp/*",
    "*/Common Workflow Language/*",
    "*/Component Pascal/*",
    "*/Cool/*",
    "*/Coq/*",
    "*/Creole/*",
    "*/Crystal/*",
    "*/Csound/*",
    "*/Csound Document/*",
    "*/Csound Score/*",
    "*/Cycript/*",
    "*/D/*",
    "*/DIGITAL Command Language/*",
    "*/DM/*",
    "*/DNS Zone/*",
    "*/DTrace/*",
    "*/Dart/*",
    "*/DataWeave/*",
    "*/Diff/*",
    "*/Dockerfile/*",
    "*/Dogescript/*",
    "*/E/*",
    "*/EBNF/*",
    "*/ECL/*",
    "*/ECLiPSe/*",
    "*/EJS/*",
    "*/EQ/*",
    "*/Eagle/*",
    "*/Easybuild/*",
    "*/Edje Data Collection/*",
    "*/Eiffel/*",
    "*/Elixir/*",
    "*/Emacs Lisp/*",
    "*/EmberScript/*",
    "*/Erlang/*.es",
    "*/Erlang/*.src",
    "*/Erlang/*.escript",
    "*/Erlang/factorial",
    "*/Erlang/release",
    "*/Erlang/*.xrl",
    "*/Erlang/filenames/*",
    "*/Erlang/*.yrl",
    "*/F#/*",
    "*/FLUX/*",
    "*/Fantom/*",
    "*/Filebench WML/*",
    "*/Filterscript/*",
    "*/Formatted/*",
    "*/Forth/*.f",
    "*/Forth/*.fth",
    "*/Forth/*.for",
    "*/Forth/*.frt",
    "*/Forth/*.4TH",
    "*/Forth/*.F",
    "*/Forth/*.fr",
    "*/Forth/*.fs",
    "*/Fortran/*",
    "*/FreeMarker/*",
    "*/Frege/*",
    "*/G-code/*",
    "*/GAMS/*",
    "*/GAP/*",
    "*/GCC Machine Description/*",
    "*/GDB/*",
    "*/GDScript/*",
    "*/GLSL/*",
    "*/GN/*",
    "*/Game Maker Language/*",
    "*/Genie/*",
    "*/Gerber Image/*",
    "*/Gnuplot/*",
    "*/Golo/*",
    "*/Gosu/*",
    "*/Grace/*",
    "*/Grammatical Framework/*",
    "*/Graph Modeling Language/*",
    "*/GraphQL/*",
    "*/Graphviz (DOT)/*",
    "*/Groovy/*",
    "*/Groovy Server Pages/*",
    "*/HCL/*",
    "*/HLSL/*",
    "*/HTML/*.inc",
    "*/HTML/*.hl",
    "*/HTML/*.st",
    "*/HTML/*.xht",
    "*/HTML+Django/*",
    "*/HTML+ECR/*",
    "*/HTML+EEX/*",
    "*/HTML+ERB/*",
    "*/HXML/*",
    "*/Hack/*.hh",
    "*/Haml/*",
    "*/Handlebars/*",
    "*/HyPhy/*",
    "*/IDL/*",
    "*/IGOR Pro/*",
    "*/INI/filenames/*",
    "*/Idris/*",
    "*/Inform 7/*",
    "*/Inno Setup/*",
    "*/Ioke/*",
    "*/Isabelle/*",
    "*/Isabelle ROOT/*",
    "*/J/hashbang",
    "*/JFlex/*",
    "*/JSON/*",
    "*/JSON5/*",
    "*/JSONLD/*",
    "*/JSONiq/*",
    "*/JSX/*",
    "*/Jasmin/*",
    "*/JavaScript/*.mjs",
    "*/JavaScript/*.xsjs",
    "*/JavaScript/*.jscad",
    "*/JavaScript/js",
    "*/JavaScript/jquery-1.4.2.min.js",
    "*/JavaScript/jquery-1.6.1.min.js",
    "*/JavaScript/*.gs",
    "*/JavaScript/*.es",
    "*/JavaScript/*.jsb",
    "*/JavaScript/*.frag",
    "*/JavaScript/*.xsjslib",
    "*/JavaScript/js2",
    "*/Jison/*",
    "*/Jison Lex/*",
    "*/Jolie/*",
    "*/Julia/julia",
    "*/Jupyter Notebook/*",
    "*/KRL/*",
    "*/KiCad Layout/*",
    "*/KiCad Legacy Layout/*",
    "*/KiCad Schematic/*",
    "*/Kit/*",
    "*/LFE/*",
    "*/LOLCODE/*",
    "*/LSL/*",
    "*/Lasso/*",
    "*/Latte/*",
    "*/Lean/*",
    "*/Less/*",
    "*/Lex/*",
    "*/Limbo/*",
    "*/Linker Script/*",
    "*/Linux Kernel Module/*",
    "*/Liquid/*",
    "*/Literate Agda/*",
    "*/Literate CoffeeScript/*",
    "*/LiveScript/*",
    "*/Logos/*",
    "*/Logtalk/*",
    "*/LookML/*",
    "*/LoomScript/*",
    "*/Lua/*",
    "*/M/*",
    "*/M4/*",
    "*/M4Sugar/*",
    "*/MAXScript/*",
    "*/MQL4/*",
    "*/MQL5/*",
    "*/MTML/*",
    "*/MUF/*",
    "*/Makefile/*",
    "*/Markdown/*",
    "*/Marko/*",
    "*/Mask/*",
    "*/Mathematica/*",
    "*/Matlab/*",
    "*/Maven POM/*",
    "*/Max/*",
    "*/MediaWiki/*",
    "*/Mercury/expr.moo",
    "*/Meson/*",
    "*/Metal/*",
    "*/Modelica/*",
    "*/Modula-2/*",
    "*/Module Management System/*",
    "*/Monkey/*",
    "*/Moocode/*",
    "*/MoonScript/*",
    "*/NCL/*",
    "*/NL/*",
    "*/NSIS/*",
    "*/Nearley/*",
    "*/Nemerle/*",
    "*/NetLinx/*",
    "*/NetLinx+ERB/*",
    "*/NetLogo/*",
    "*/NewLisp/*",
    "*/Nextflow/*",
    "*/Nginx/*",
    "*/Nim/*",
    "*/Nit/*",
    "*/Nix/*",
    "*/Nu/*",
    "*/OCaml/*",
    "*/Objective-C/*",
    "*/Objective-C++/*",
    "*/Objective-J/*",
    "*/Omgrofl/*",
    "*/Opa/*",
    "*/Opal/*",
    "*/OpenCL/*",
    "*/OpenEdge ABL/*",
    "*/OpenRC runscript/*",
    "*/OpenSCAD/*",
    "*/Org/*",
    "*/Ox/*",
    "*/Oz/*",
    "*/P4/*",
    "*/PAWN/*",
    "*/PHP/*.inc",
    "*/PHP/*.fcgi",
    "*/PHP/php*",
    "*/PHP/filenames/.php_cs",
    "*/PHP/filenames/.php_cs.dist",
    "*/POV-Ray SDL/*",
    "*/Pan/*",
    "*/Papyrus/*",
    "*/Parrot Assembly/*",
    "*/Parrot Internal Representation/*",
    "*/Pascal/*",
    "*/Pep8/*",
    "*/Perl/*",
    "*/Perl 6/*",
    "*/Pic/*",
    "*/Pickle/*",
    "*/PicoLisp/*",
    "*/PigLatin/*",
    "*/Pike/*",
    "*/Pod/*",
    "*/PogoScript/*",
    "*/Pony/*",
    "*/PostCSS/*",
    "*/PostScript/*",
    "*/PowerBuilder/*",
    "*/Prolog/*",
    "*/Propeller Spin/*",
    "*/Protocol Buffer/*",
    "*/Public Key/*",
    "*/Pug/*",
    "*/PureBasic/*",
    "*/PureScript/*",
    "*/Python/*.pyi",
    "*/Python/*.rpy",
    "*/Python/python*",
    "*/Python/*.gypi",
    "*/Python/filenames/*",
    "*/Python/*.spec",
    "*/Python/*.pyde",
    "*/Python/*.cgi",
    "*/Python/*.bzl",
    "*/Python/*.pyp",
    "*/Python/*.fcgi",
    "*/QML/*",
    "*/QMake/qmake",
    "*/QMake/functions.pri",
    "*/R/*",
    "*/RAML/*",
    "*/RDoc/*",
    "*/REXX/*",
    "*/RMarkdown/*",
    "*/RPC/*",
    "*/RPM Spec/*",
    "*/RUNOFF/*",
    "*/Racket/*",
    "*/Ragel/*",
    "*/Rascal/*",
    "*/Reason/*",
    "*/Rebol/*",
    "*/Red/*",
    "*/Regular Expression/*",
    "*/RenderScript/*",
    "*/Ring/*",
    "*/RobotFramework/*",
    "*/Roff/*",
    "*/Ruby/*spec",
    "*/Ruby/rexpl",
    "*/Ruby/ruby*",
    "*/Ruby/*jbuilder",
    "*/Ruby/filenames/*",
    "*/Ruby/*.fcgi",
    "*/Ruby/*.rabl",
    "*/Ruby/macruby",
    "*/Ruby/*.rake",
    "*/Ruby/shoes-swt",
    "*/Rust/*",
    "*/SCSS/*",
    "*/SMT/*",
    "*/SPARQL/*",
    "*/SQF/*",
    "*/SQL/hostcache_set_state.inc",
    "*/SQL/AvailableInSearchSel.prc",
    "*/SQLPL/check_reorg.sql",
    "*/SQLPL/runstats.sql",
    "*/SQLPL/sleep.sql",
    "*/SQLPL/create_stuff.sql",
    "*/SRecode Template/*",
    "*/STON/*",
    "*/Sage/*",
    "*/SaltStack/*",
    "*/Sass/*",
    "*/Scala/*",
    "*/Scaml/*",
    "*/Scheme/*",
    "*/Scilab/*",
    "*/ShaderLab/*",
    "*/Shell/*.command",
    "*/Shell/*zsh",
    "*/Shell/99-bottles-of-beer",
    "*/Shell/*cgi",
    "*/Shell/plugin",
    "*/Shell/*bash",
    "*/Shell/sh",
    "*/Shell/filenames/*",
    "*/Shell/sbt",
    "*/Shell/*.tool",
    "*/Shell/string-chopping",
    "*/ShellSession/*",
    "*/Shen/*",
    "*/Slash/*",
    "*/Slim/*",
    "*/Smali/*",
    "*/Smalltalk/*.cs",
    "*/SourcePawn/*",
    "*/Squirrel/*",
    "*/Stan/*",
    "*/Standard ML/*",
    "*/Stata/*",
    "*/Stylus/*",
    "*/SubRip Text/*",
    "*/Sublime Text Config/*",
    "*/SugarSS/*",
    "*/SuperCollider/*",
    "*/SystemVerilog/*",
    "*/TI Program/*",
    "*/TLA/*",
    "*/TOML/*",
    "*/TXL/*",
    "*/Tcl/*",
    "*/TeX/*",
    "*/Tea/*",
    "*/Terra/*",
    "*/Text/*",
    "*/Thrift/*",
    "*/Turing/*",
    "*/Turtle/*",
    "*/Type Language/*",
    "*/TypeScript/*.tsx",
    "*/Unity3D Asset/*",
    "*/Unix Assembly/*",
    "*/Uno/*",
    "*/UnrealScript/*",
    "*/UrWeb/*",
    "*/VCL/*",
    "*/VHDL/*",
    "*/Vim script/*",
    "*/Visual Basic/*",
    "*/Volt/*",
    "*/Wavefront Material/*",
    "*/Wavefront Object/*",
    "*/Web Ontology Language/*",
    "*/WebAssembly/*",
    "*/WebIDL/*",
    "*/World of Warcraft Addon Data/*",
    "*/X10/*",
    "*/XC/*",
    "*/XCompose/*",
    "*/XML/*",
    "*/XPM/*",
    "*/XPages/*",
    "*/XProc/*",
    "*/XQuery/*",
    "*/XS/*",
    "*/XSLT/*",
    "*/Xojo/*",
    "*/YAML/*",
    "*/YANG/*",
    "*/YARA/*",
    "*/Zephir/*",
    "*/Zimpl/*",
    "*/desktop/*",
    "*/eC/*",
    "*/edn/*",
    "*/fish/*",
    "*/reStructuredText/*",
    "*/sed/*",
    "*/wdl/*",
    "*/wisp/*",
    "*/xBase/*"
)
