// Copyright 2018 Sourcerer Inc. All Rights Reserved.
// Author: Alexander Surkov (alex@sourcerer.io)

package test.tests.extractors

/**
 * A list of all file names whose language recognition needs to be checked
 * or fixed.
 */
var ignoredSamplesWildcards = listOf(
    "*/1C Enterprise/*",
    "*/ABAP/*",
    "*/AppleScript/*",
    "*/Apex/*",
    "*/APL/*",
    "*/API Blueprint/*",
    "*/AngelScript/*",
    "*/Alloy/*",
    "*/Apollo Guidance Computer/*",
    "*/ASN.1/*",
    "*/Awk/*",
    "*/Ant Build System/*",
    "*/Assembly/*",
    "*/Alpine Abuild/*",
    "*/AspectJ/*",
    "*/AMPL/*",
    "*/AutoHotkey/*",
    "*/AsciiDoc/*",
    "*/Agda/*",
    "*/ATS/*",
    "*/ApacheConf/*",
    "*/ActionScript/*",
    "*/AGS Script/*",
    "*/Adobe Font Metrics/*",
    "*/Brightscript/*",
    "*/Bluespec/*",
    "*/Blade/*",
    "*/Brainfuck/*",
    "*/BlitzBasic/*",
    "*/BitBake/*",
    "*/Ballerina/*",
    "*/BlitzMax/*",
    "*/C/*.h",
    "*/C/script",
    "*/C/*.cats",
    "*/C/*.H",
    "*/C#/*.cs",
    "*/C++/*.inc",
    "*/C++/*.re",
    "*/C++/*.ino",
    "*/C++/*.ipp",
    "*/CartoCSS/*.mss",
    "*/CLIPS/*",
    "*/CMake/*",
    "*/COBOL/*",
    "*/CSON/*",
    "*/CSV/*",
    "*/CWeb/*",
    "*/CartoCSS/*",
    "*/Ceylon/*",
    "*/Chapel/*",
    "*/Charity/*",
    "*/Cirru/*",
    "*/Clarion/*",
    "*/Clean/*",
    "*/Click/*",
    "*/Clojure/*",
    "*/Closure Templates/*",
    "*/CoNLL-U/*",
    "*/CoffeeScript/*",
    "*/ColdFusion/*",
    "*/ColdFusion CFC/*",
    "*/Common Lisp/*",
    "*/Common Workflow Language/*",
    "*/Component Pascal/*",
    "*/Cool/*",
    "*/Coq/*",
    "*/Creole/*",
    "*/Crystal/*",
    "*/Csound/*",
    "*/Csound Document/*",
    "*/Csound Score/*",
    "*/Cuda/*",
    "*/Cycript/*",
    "*/D/*",
    "*/DIGITAL Command Language/*",
    "*/DM/*",
    "*/DNS Zone/*",
    "*/DTrace/*",
    "*/Dart/*",
    "*/DataWeave/*",
    "*/Diff/*",
    "*/Dockerfile/*",
    "*/Dogescript/*",
    "*/E/*",
    "*/EBNF/*",
    "*/ECL/*",
    "*/ECLiPSe/*",
    "*/EJS/*",
    "*/EQ/*",
    "*/Eagle/*",
    "*/Easybuild/*",
    "*/Edje Data Collection/*",
    "*/Eiffel/*",
    "*/Elixir/*",
    "*/Elm/*",
    "*/Emacs Lisp/*",
    "*/EmberScript/*",
    "*/Erlang/*",
    "*/F#/*",
    "*/FLUX/*",
    "*/Fantom/*",
    "*/Filebench WML/*",
    "*/Filterscript/*",
    "*/Formatted/*",
    "*/Forth/*",
    "*/Fortran/*",
    "*/FreeMarker/*",
    "*/Frege/*",
    "*/G-code/*",
    "*/GAMS/*",
    "*/GAP/*",
    "*/GCC Machine Description/*",
    "*/GDB/*",
    "*/GDScript/*",
    "*/GLSL/*",
    "*/GN/*",
    "*/Game Maker Language/*",
    "*/Genie/*",
    "*/Gerber Image/*",
    "*/Gnuplot/*",
    "*/Go/*",
    "*/Golo/*",
    "*/Gosu/*",
    "*/Grace/*",
    "*/Gradle/*",
    "*/Grammatical Framework/*",
    "*/Graph Modeling Language/*",
    "*/GraphQL/*",
    "*/Graphviz (DOT)/*",
    "*/Groovy/*",
    "*/Groovy Server Pages/*",
    "*/HCL/*",
    "*/HLSL/*",
    "*/HTML/*",
    "*/HTML+Django/*",
    "*/HTML+ECR/*",
    "*/HTML+EEX/*",
    "*/HTML+ERB/*",
    "*/HXML/*",
    "*/Hack/*",
    "*/Haml/*",
    "*/Handlebars/*",
    "*/Haskell/*",
    "*/Hy/*",
    "*/HyPhy/*",
    "*/IDL/*",
    "*/IGOR Pro/*",
    "*/INI/*",
    "*/Idris/*",
    "*/Inform 7/*",
    "*/Inno Setup/*",
    "*/Ioke/*",
    "*/Isabelle/*",
    "*/Isabelle ROOT/*",
    "*/J/*",
    "*/JFlex/*",
    "*/JSON/*",
    "*/JSON5/*",
    "*/JSONLD/*",
    "*/JSONiq/*",
    "*/JSX/*",
    "*/Jasmin/*",
    "*/Java/*",
    "*/JavaScript/*",
    "*/Jison/*",
    "*/Jison Lex/*",
    "*/Jolie/*",
    "*/Julia/*",
    "*/Jupyter Notebook/*",
    "*/KRL/*",
    "*/KiCad Layout/*",
    "*/KiCad Legacy Layout/*",
    "*/KiCad Schematic/*",
    "*/Kit/*",
    "*/Kotlin/*",
    "*/LFE/*",
    "*/LOLCODE/*",
    "*/LSL/*",
    "*/Lasso/*",
    "*/Latte/*",
    "*/Lean/*",
    "*/Less/*",
    "*/Lex/*",
    "*/Limbo/*",
    "*/Linker Script/*",
    "*/Linux Kernel Module/*",
    "*/Liquid/*",
    "*/Literate Agda/*",
    "*/Literate CoffeeScript/*",
    "*/LiveScript/*",
    "*/Logos/*",
    "*/Logtalk/*",
    "*/LookML/*",
    "*/LoomScript/*",
    "*/Lua/*",
    "*/M/*",
    "*/M4/*",
    "*/M4Sugar/*",
    "*/MAXScript/*",
    "*/MQL4/*",
    "*/MQL5/*",
    "*/MTML/*",
    "*/MUF/*",
    "*/Makefile/*",
    "*/Markdown/*",
    "*/Marko/*",
    "*/Mask/*",
    "*/Mathematica/*",
    "*/Matlab/*",
    "*/Maven POM/*",
    "*/Max/*",
    "*/MediaWiki/*",
    "*/Mercury/*",
    "*/Meson/*",
    "*/Metal/*",
    "*/Modelica/*",
    "*/Modula-2/*",
    "*/Module Management System/*",
    "*/Monkey/*",
    "*/Moocode/*",
    "*/MoonScript/*",
    "*/NCL/*",
    "*/NL/*",
    "*/NSIS/*",
    "*/Nearley/*",
    "*/Nemerle/*",
    "*/NetLinx/*",
    "*/NetLinx+ERB/*",
    "*/NetLogo/*",
    "*/NewLisp/*",
    "*/Nextflow/*",
    "*/Nginx/*",
    "*/Nim/*",
    "*/Nit/*",
    "*/Nix/*",
    "*/Nu/*",
    "*/OCaml/*",
    "*/Objective-C/*",
    "*/Objective-C++/*",
    "*/Objective-J/*",
    "*/Omgrofl/*",
    "*/Opa/*",
    "*/Opal/*",
    "*/OpenCL/*",
    "*/OpenEdge ABL/*",
    "*/OpenRC runscript/*",
    "*/OpenSCAD/*",
    "*/Org/*",
    "*/Ox/*",
    "*/Oxygene/*",
    "*/Oz/*",
    "*/P4/*",
    "*/PAWN/*",
    "*/PHP/*",
    "*/PLSQL/*",
    "*/PLpgSQL/*",
    "*/POV-Ray SDL/*",
    "*/Pan/*",
    "*/Papyrus/*",
    "*/Parrot Assembly/*",
    "*/Parrot Internal Representation/*",
    "*/Pascal/*",
    "*/Pep8/*",
    "*/Perl/*",
    "*/Perl 6/*",
    "*/Pic/*",
    "*/Pickle/*",
    "*/PicoLisp/*",
    "*/PigLatin/*",
    "*/Pike/*",
    "*/Pod/*",
    "*/PogoScript/*",
    "*/Pony/*",
    "*/PostCSS/*",
    "*/PostScript/*",
    "*/PowerBuilder/*",
    "*/PowerShell/*",
    "*/Processing/*",
    "*/Prolog/*",
    "*/Propeller Spin/*",
    "*/Protocol Buffer/*",
    "*/Public Key/*",
    "*/Pug/*",
    "*/Puppet/*",
    "*/PureBasic/*",
    "*/PureScript/*",
    "*/Python/*",
    "*/QML/*",
    "*/QMake/*",
    "*/R/*",
    "*/RAML/*",
    "*/RDoc/*",
    "*/REXX/*",
    "*/RMarkdown/*",
    "*/RPC/*",
    "*/RPM Spec/*",
    "*/RUNOFF/*",
    "*/Racket/*",
    "*/Ragel/*",
    "*/Rascal/*",
    "*/Reason/*",
    "*/Rebol/*",
    "*/Red/*",
    "*/Regular Expression/*",
    "*/RenderScript/*",
    "*/Ring/*",
    "*/RobotFramework/*",
    "*/Roff/*",
    "*/Ruby/*",
    "*/Rust/*",
    "*/SAS/*",
    "*/SCSS/*",
    "*/SMT/*",
    "*/SPARQL/*",
    "*/SQF/*",
    "*/SQL/*",
    "*/SQLPL/*",
    "*/SRecode Template/*",
    "*/STON/*",
    "*/Sage/*",
    "*/SaltStack/*",
    "*/Sass/*",
    "*/Scala/*",
    "*/Scaml/*",
    "*/Scheme/*",
    "*/Scilab/*",
    "*/ShaderLab/*",
    "*/Shell/*",
    "*/ShellSession/*",
    "*/Shen/*",
    "*/Slash/*",
    "*/Slim/*",
    "*/Smali/*",
    "*/Smalltalk/*",
    "*/SourcePawn/*",
    "*/Squirrel/*",
    "*/Stan/*",
    "*/Standard ML/*",
    "*/Stata/*",
    "*/Stylus/*",
    "*/SubRip Text/*",
    "*/Sublime Text Config/*",
    "*/SugarSS/*",
    "*/SuperCollider/*",
    "*/Swift/*",
    "*/SystemVerilog/*",
    "*/TI Program/*",
    "*/TLA/*",
    "*/TOML/*",
    "*/TXL/*",
    "*/Tcl/*",
    "*/TeX/*",
    "*/Tea/*",
    "*/Terra/*",
    "*/Text/*",
    "*/Thrift/*",
    "*/Turing/*",
    "*/Turtle/*",
    "*/Type Language/*",
    "*/TypeScript/*",
    "*/Unity3D Asset/*",
    "*/Unix Assembly/*",
    "*/Uno/*",
    "*/UnrealScript/*",
    "*/UrWeb/*",
    "*/VCL/*",
    "*/VHDL/*",
    "*/Verilog/*",
    "*/Vim script/*",
    "*/Visual Basic/*",
    "*/Volt/*",
    "*/Vue/*",
    "*/Wavefront Material/*",
    "*/Wavefront Object/*",
    "*/Web Ontology Language/*",
    "*/WebAssembly/*",
    "*/WebIDL/*",
    "*/World of Warcraft Addon Data/*",
    "*/X10/*",
    "*/XC/*",
    "*/XCompose/*",
    "*/XML/*",
    "*/XPM/*",
    "*/XPages/*",
    "*/XProc/*",
    "*/XQuery/*",
    "*/XS/*",
    "*/XSLT/*",
    "*/Xojo/*",
    "*/Xtend/*",
    "*/YAML/*",
    "*/YANG/*",
    "*/YARA/*",
    "*/Zephir/*",
    "*/Zimpl/*",
    "*/desktop/*",
    "*/eC/*",
    "*/edn/*",
    "*/fish/*",
    "*/reStructuredText/*",
    "*/sed/*",
    "*/wdl/*",
    "*/wisp/*",
    "*/xBase/*"
)
