// Copyright 2018 Sourcerer Inc. All Rights Reserved.
// Author: Alexander Surkov (alex@sourcerer.io)

package app.extractors

object Lang {
    const val ActionScript = "actionscript" // ActionScript
    const val AngelScript = "angelscript"  // AngelScript
    const val Assembly = "assembly" // Assembly
    const val Arduino = "assembly" // Arduino
    const val C = "c" // C
    const val CSharp = "csharp" // C#
    const val CSS = "css" // CSS
    const val CPlusPlus = "cpp" // C++
    const val Clojure = "clojure" // Clojure
    const val COBOL = "cobol" // COBOL
    const val CoffeeScript = "coffeescript" // CoffeeScript
    const val CommonLisp = "lisp" // Common Lisp
    const val Cuda = "cuda" // Cuda
    const val D = "d" // D
    const val DOSBatch = "dosbatch" // DOS Batch
    const val DTrace = "dtrace" // DTrace
    const val Elixir = "elixir" // Elixir
    const val Elm = "elm" // Elm
    const val EmacsLisp = "emacslisp" // Emacs Lisp
    const val Erlang = "erlang" // Erlang
    const val Factor = "factor" // Factor
    const val FilebenchWML = "filebench_wml" // Filebench WML
    const val Filterscript = "filterscript" // Filterscript
    const val Forth = "forth" // Forth
    const val Fortran = "fortran" // Fortran
    const val FSharp = "fsharp" // F#
    const val GLSL = "glsl" // GLSL
    const val Go = "go" // Go
    const val Gradle = "gradle" // Gradle
    const val Groovy = "groovy" // Groovy
    const val Hack = "hack" // Hack
    const val Haskell = "haskell" // Haskell
    const val Haxe = "haxe" // Haxe
    const val HTML = "html" // HTML
    const val Hy = "hy" // Hy
    const val IDL = "idl" // IDL
    const val INI = "ini" // INI
    const val J = "j" // J
    const val Java = "java" // Java
    const val JavaScript = "javascript" // JavaScript
    const val Julia = "julia" // Julia
    const val Kotlin = "kotlin" // Kotlin
    const val Limbo = "limbo" // Limbo
    const val Lex = "lex" // Lex
    const val Lua = "lua" // Lua
    const val M = "m" // M
    const val Makefile = "makefile" // Makefile
    const val Mathematica = "mathematica" // Mathematica
    const val Matlab = "matlab" // Matlab
    const val MavenPOM = "maven" // Maven POM
    const val MUF = "muf" // MUF
    const val Mercury = "mercury" // Mercury
    const val NewLisp = "newlisp" // NewLisp
    const val ObjectiveC = "objectivec" // Objective-C
    const val OCaml = "ocaml" // OCaml
    const val Oxygene = "oxygene" // Oxygene
    const val Pascal = "pascal" // Pascal
    const val Perl = "perl" // Perl
    const val Perl6 = "perl6" // Perl 6
    const val PHP = "php" // PHP
    const val PicoLisp = "picolisp" // PicoLisp
    const val PLpgSQL = "plpgsql" // PLpgSQL
    const val PLSQL = "plsql" // PLSQL
    const val POVRaySDL = "pov-ray_sdl" // POV-Ray SDL
    const val PowerShell = "powershell" // PowerShell
    const val Puppet = "puppet" // Puppet
    const val Processing = "processing" // Processing
    const val Prolog = "prolog" // Prolog
    const val Python = "python" // Python
    const val QMake = "qmake" // QMake
    const val QML = "qml" // QML
    const val R = "r" // R
    const val Rebol = "rebol" // Rebol
    const val RenderScript = "renderscript" // RenderScript
    const val RenPy = "renpy" // Ren'Py
    const val Roff = "roff" // Roff
    const val Ruby = "ruby" // Ruby
    const val Rust = "rust" // Rust
    const val SAS = "sas" // SAS
    const val Scala = "scala" // Scala
    const val Scheme = "scheme" // Scheme
    const val Shell = "shell" // Shell
    const val Smalltalk = "smalltalk" // Smalltalk
    const val StandardML = "standard_ml" // Standard ML
    const val SQL = "sql" // SQL
    const val SQLPL = "sqlpl" // SQLPL
    const val SuperCollider = "supercollider" // SuperCollider
    const val Swift = "swift" // Swift
    const val Tcl = "tcl" // Tcl
    const val TeX = "tex" // TeX
    const val TypeScript = "typescript" // TypeScript
    const val Verilog = "verilog" // Verilog
    const val VisualBasic = "visualbasic" // Visual Basic
    const val VisualBasicForApps = "visualbasicforapps" // Visual Basic for Applications
    const val VHDL = "vhdl" // VHDL
    const val VimL = "viml" // Vim L
    const val Vue = "vue" // Vue
    const val WolframLanguage = "wolframlanguage" // Wolfram Language
    const val XML = "xml" // XML
    const val XPM = "xpm" // XPM
    const val Xtend = "xtend" // Xtend
}
