// Copyright 2018 Sourcerer Inc. All Rights Reserved.
// Author: Alexander Surkov (alex@sourcerer.io)

package app.extractors

object Lang {
    const val ACTIONSCRIPT = "actionscript"  // ActionScript
    const val ANGELSCRIPT = "angelscript"  // AngelScript
    const val ASSEMBLY = "assembly"  // Assembly
    const val ARDUINO = "arduino"  // Arduino
    const val C = "c"  // C
    const val COQ = "coq"  // Coq
    const val CPP = "cpp"  // C++
    const val CRYSTAL = "crystal"  // Crystal
    const val CSHARP = "csharp"  // C#
    const val CSS = "css"  // CSS
    const val CLOJURE = "clojure"  // Clojure
    const val COBOL = "cobol"  // COBOL
    const val COFFEESCRIPT = "coffeescript"  // CoffeeScript
    const val COMMONLISP = "lisp"  // Common Lisp
    const val CUDA = "cuda"  // Cuda
    const val D = "d"  // D
    const val DART = "dart"  // Dart
    const val DM = "dm"  // DM Language
    const val DOSBATCH = "dosbatch"  // DOS Batch
    const val DTRACE = "dtrace"  // DTrace
    const val ELIXIR = "elixir"  // Elixir
    const val ELM = "elm"  // Elm
    const val EMACSLISP = "emacslisp"  // Emacs Lisp
    const val ERLANG = "erlang"  // Erlang
    const val FACTOR = "factor"  // Factor
    const val FILEBENCHWML = "filebench_wml"  // Filebench WML
    const val FILTERSCRIPT = "filterscript"  // Filterscript
    const val FORTH = "forth"  // Forth
    const val FORTRAN = "fortran"  // Fortran
    const val FSHARP = "fsharp"  // F#
    const val GLSL = "glsl"  // GLSL
    const val GO = "go"  // Go
    const val GRADLE = "gradle"  // Gradle
    const val GROOVY = "groovy"  // Groovy
    const val HACK = "hack"  // Hack
    const val HASKELL = "haskell"  // Haskell
    const val HAXE = "haxe"  // Haxe
    const val HTML = "html"  // HTML
    const val HY = "hy"  // Hy
    const val IDL = "idl"  // IDL
    const val INI = "ini"  // INI
    const val J = "j"  // J
    const val JAVA = "java"  // Java
    const val JAVASCRIPT = "javascript"  // JavaScript
    const val JULIA = "julia"  // Julia
    const val KOTLIN = "kotlin"  // Kotlin
    const val LIMBO = "limbo"  // Limbo
    const val LEX = "lex"  // Lex
    const val LUA = "lua"  // Lua
    const val M = "m"  // M
    const val MAKEFILE = "makefile"  // Makefile
    const val MATHEMATICA = "mathematica"  // Mathematica
    const val MATLAB = "matlab"  // Matlab
    const val MAVENPOM = "maven"  // Maven POM
    const val MUF = "muf"  // MUF
    const val MERCURY = "mercury"  // Mercury
    const val NEWLISP = "newlisp"  // NewLisp
    const val OBJECTIVEC = "objectivec"  // Objective-C
    const val OCAML = "ocaml"  // OCaml
    const val OXYGENE = "oxygene"  // Oxygene
    const val PASCAL = "pascal"  // Pascal
    const val PERL = "perl"  // Perl
    const val PERL6 = "perl6"  // Perl 6
    const val PHP = "php"  // PHP
    const val PICOLISP = "picolisp"  // PicoLisp
    const val PLPGSQL = "plpgsql"  // PLpgSQL
    const val PLSQL = "plsql"  // PLSQL
    const val POVRAYSDL = "pov-ray_sdl"  // POV-Ray SDL
    const val POWERSHELL = "powershell"  // PowerShell
    const val PUPPET = "puppet"  // Puppet
    const val PROCESSING = "processing"  // Processing
    const val PROLOG = "prolog"  // Prolog
    const val PYTHON = "python"  // Python
    const val QMAKE = "qmake"  // QMake
    const val QML = "qml"  // QML
    const val R = "r"  // R
    const val REBOL = "rebol"  // Rebol
    const val RENDERSCRIPT = "renderscript"  // RenderScript
    const val RENPY = "renpy"  // Ren'Py
    const val ROFF = "roff"  // Roff
    const val RUBY = "ruby"  // Ruby
    const val RUST = "rust"  // Rust
    const val SAS = "sas"  // SAS
    const val SCALA = "scala"  // Scala
    const val SCHEME = "scheme"  // Scheme
    const val SHELL = "shell"  // Shell
    const val SMALLTALK = "smalltalk"  // Smalltalk
    const val SOLIDITY = "solidity"  // Solidity
    const val SQL = "sql"  // SQL
    const val SQLPL = "sqlpl"  // SQLPL
    const val STANDARDML = "standard_ml"  // Standard ML
    const val SUPERCOLLIDER = "supercollider"  // SuperCollider
    const val SWIFT = "swift"  // Swift
    const val TCL = "tcl"  // Tcl
    const val TEX = "tex"  // TeX
    const val TYPESCRIPT = "typescript"  // TypeScript
    const val VERILOG = "verilog"  // Verilog
    const val VISUALBASIC = "visualbasic"  // Visual Basic
    const val VBA = "visualbasicforapps"  // Visual Basic for Applications
    const val VHDL = "vhdl"  // VHDL
    const val VIML = "viml"  // Vim L
    const val VUE = "vue"  // Vue
    const val SVELTE = "svelte" // Svelte
    const val WOLFRAM = "wolframlanguage"  // Wolfram Language
    const val XML = "xml"  // XML
    const val XPM = "xpm"  // XPM
    const val XTEND = "xtend"  // Xtend
}
