// Copyright 2018 Sourcerer Inc. All Rights Reserved.
// Author: Alexander Surkov (alex@sourcerer.io),

// Inspired by GitHub Liguist heuristics (https://github.com/github/linguist).

package app.hashers

import app.RegexMeasured

const val CLASS_TAG = "Vendors-"

/**
 * List of regexps that are matched against file pathname. Used to filter out
 * vendor specific files from the repo statistics.
 */
val VendorConventions = listOf(
    // Caches
    RegexMeasured(CLASS_TAG, """(^|/)cache/"""),

    // Dependencies
    RegexMeasured(CLASS_TAG, """^[Dd]ependencies/"""),

    // Distributions
    RegexMeasured(CLASS_TAG, """(^|/)dist/"""),

    // C deps
    RegexMeasured(CLASS_TAG, """^deps/"""),
    RegexMeasured(CLASS_TAG, """(^|/)configure$"""),
    RegexMeasured(CLASS_TAG, """(^|/)config.guess$"""),
    RegexMeasured(CLASS_TAG, """(^|/)config.sub$"""),

    // stuff autogenerated by autoconf - still C deps
    RegexMeasured(CLASS_TAG, """(^|/)aclocal.m4"""),
    RegexMeasured(CLASS_TAG, """(^|/)libtool.m4"""),
    RegexMeasured(CLASS_TAG, """(^|/)ltoptions.m4"""),
    RegexMeasured(CLASS_TAG, """(^|/)ltsugar.m4"""),
    RegexMeasured(CLASS_TAG, """(^|/)ltversion.m4"""),
    RegexMeasured(CLASS_TAG, """(^|/)lt~obsolete.m4"""),

    // Linters
    RegexMeasured(CLASS_TAG, """cpplint.py"""),

    // Node dependencies
    RegexMeasured(CLASS_TAG, """node_modules/"""),

    // Bower Components
    RegexMeasured(CLASS_TAG, """bower_components/"""),

    // Erlang bundles
    RegexMeasured(CLASS_TAG, """^rebar$"""),
    RegexMeasured(CLASS_TAG, """erlang.mk"""),

    // Go dependencies
    RegexMeasured(CLASS_TAG, """Godeps/_workspace/"""),

    // GNU indent profiles
    RegexMeasured(CLASS_TAG, """.indent.pro"""),

    // Minified JavaScript and CSS
    RegexMeasured(CLASS_TAG, """(\.|-)min\.(js|css)$"""),

    // Stylesheets imported from packages
    RegexMeasured(CLASS_TAG, """([^\s]*)import\.(css|less|scss|styl)$"""),

    // Bootstrap css and js
    RegexMeasured(CLASS_TAG, """(^|/)bootstrap([^.]*)\.(js|css|less|scss|styl)$"""),
    RegexMeasured(CLASS_TAG, """(^|/)custom\.bootstrap([^\s]*)(js|css|less|scss|styl)$"""),

    // Font Awesome
    RegexMeasured(CLASS_TAG, """(^|/)font-awesome\.(css|less|scss|styl)$"""),
    RegexMeasured(CLASS_TAG, """(^|/)font-awesome/.*\.(css|less|scss|styl)$"""),

    // Foundation css
    RegexMeasured(CLASS_TAG, """(^|/)foundation\.(css|less|scss|styl)$"""),

    // Normalize.css
    RegexMeasured(CLASS_TAG, """(^|/)normalize\.(css|less|scss|styl)$"""),

    // Skeleton.css
    RegexMeasured(CLASS_TAG, """(^|/)skeleton\.(css|less|scss|styl)$"""),

    // Bourbon css
    RegexMeasured(CLASS_TAG, """(^|/)[Bb]ourbon/.*\.(css|less|scss|styl)$"""),

    // Animate.css
    RegexMeasured(CLASS_TAG, """(^|/)animate\.(css|less|scss|styl)$"""),

    // Materialize.css
    RegexMeasured(CLASS_TAG, """(^|/)materialize\.(css|less|scss|styl|js)$"""),

    // Select2
    RegexMeasured(CLASS_TAG, """(^|/)select2/.*\.(css|scss|js)$"""),

    // Vendored dependencies
    RegexMeasured(CLASS_TAG, """third[-_]?party/"""),
    RegexMeasured(CLASS_TAG, """3rd[-_]?party/"""),
    RegexMeasured(CLASS_TAG, """vendors?/"""),
    RegexMeasured(CLASS_TAG, """extern(al)?/"""),
    RegexMeasured(CLASS_TAG, """(^|/)[Vv]+endor/"""),

    // Debian packaging
    RegexMeasured(CLASS_TAG, """^debian/"""),

    // Haxelib projects often contain a neko bytecode file named run.n
    RegexMeasured(CLASS_TAG, """run.n$"""),

    // Bootstrap Datepicker
    RegexMeasured(CLASS_TAG, """bootstrap-datepicker/"""),

    // Commonly Bundled JavaScript frameworks

    // jQuery
    RegexMeasured(CLASS_TAG, """(^|/)jquery([^.]*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)jquery\-\d\.\d+(\.\d+)?\.js$"""),

    // jQuery UI
    RegexMeasured(CLASS_TAG, """(^|/)jquery\-ui(\-\d\.\d+(\.\d+)?)?(\.\w+)?\.(js|css)$"""),
    RegexMeasured(CLASS_TAG, """(^|/)jquery\.(ui|effects)\.([^.]*)\.(js|css)$"""),

    // jQuery Gantt
    RegexMeasured(CLASS_TAG, """jquery.fn.gantt.js"""),

    // jQuery fancyBox
    RegexMeasured(CLASS_TAG, """jquery.fancybox.(js|css)"""),

    // Fuel UX
    RegexMeasured(CLASS_TAG, """fuelux.js"""),

    // jQuery File Upload
    RegexMeasured(CLASS_TAG, """(^|/)jquery\.fileupload(-\w+)?\.js$"""),

    // jQuery dataTables
    RegexMeasured(CLASS_TAG, """jquery.dataTables.js"""),

    // bootboxjs
    RegexMeasured(CLASS_TAG, """bootbox.js"""),

    // pdf-worker
    RegexMeasured(CLASS_TAG, """pdf.worker.js"""),

    // Slick
    RegexMeasured(CLASS_TAG, """(^|/)slick\.\w+.js$"""),

    // Leaflet plugins
    RegexMeasured(CLASS_TAG, """(^|/)Leaflet\.Coordinates-\d+\.\d+\.\d+\.src\.js$"""),
    RegexMeasured(CLASS_TAG, """leaflet.draw-src.js"""),
    RegexMeasured(CLASS_TAG, """leaflet.draw.css"""),
    RegexMeasured(CLASS_TAG, """Control.FullScreen.css"""),
    RegexMeasured(CLASS_TAG, """Control.FullScreen.js"""),
    RegexMeasured(CLASS_TAG, """leaflet.spin.js"""),
    RegexMeasured(CLASS_TAG, """wicket-leaflet.js"""),

    // Sublime Text workspace files
    RegexMeasured(CLASS_TAG, """.sublime-project"""),
    RegexMeasured(CLASS_TAG, """.sublime-workspace"""),

    // VS Code workspace files
    RegexMeasured(CLASS_TAG, """.vscode"""),

    // Prototype
    RegexMeasured(CLASS_TAG, """(^|/)prototype(.*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)effects\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)controls\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)dragdrop\.js$"""),

    // Typescript definition files
    RegexMeasured(CLASS_TAG, """(.*?)\.d\.ts$"""),

    // MooTools
    RegexMeasured(CLASS_TAG, """(^|/)mootools([^.]*)\d+\.\d+.\d+([^.]*)\.js$"""),

    // Dojo
    RegexMeasured(CLASS_TAG, """(^|/)dojo\.js$"""),

    // MochiKit
    RegexMeasured(CLASS_TAG, """(^|/)MochiKit\.js$"""),

    // YUI
    RegexMeasured(CLASS_TAG, """(^|/)yahoo-([^.]*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)yui([^.]*)\.js$"""),

    // WYS editors
    RegexMeasured(CLASS_TAG, """(^|/)ckeditor\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)tiny_mce([^.]*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)tiny_mce/(langs|plugins|themes|utils)"""),

    // Ace Editor
    RegexMeasured(CLASS_TAG, """(^|/)ace-builds/"""),

    // Fontello CSS files
    RegexMeasured(CLASS_TAG, """(^|/)fontello(.*?)\.css$"""),

    // MathJax
    RegexMeasured(CLASS_TAG, """(^|/)MathJax/"""),

    // Chart.js
    RegexMeasured(CLASS_TAG, """(^|/)Chart\.js$"""),

    // CodeMirror
    RegexMeasured(CLASS_TAG, """(^|/)[Cc]ode[Mm]irror/(\d+\.\d+/)?(lib|mode|theme|addon|keymap|demo)"""),

    // SyntaxHighlighter - http://alexgorbatchev.com/
    RegexMeasured(CLASS_TAG, """(^|/)shBrush([^.]*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)shCore\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)shLegacy\.js$"""),

    // AngularJS
    RegexMeasured(CLASS_TAG, """(^|/)angular([^.]*)\.js$"""),

    // D3.js
    RegexMeasured(CLASS_TAG, """(^|\/)d3(\.v\d+)?([^.]*)\.js$"""),

    // React
    RegexMeasured(CLASS_TAG, """(^|/)react(-[^.]*)?\.js$"""),

    // flow-typed
    RegexMeasured(CLASS_TAG, """(^|/)flow-typed/.*\.js$"""),

    // Modernizr
    RegexMeasured(CLASS_TAG, """(^|/)modernizr\-\d\.\d+(\.\d+)?\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)modernizr\.custom\.\d+\.js$"""),

    // Knockout
    RegexMeasured(CLASS_TAG, """(^|/)knockout-(\d+\.){3}(debug\.)?js$"""),

    // Python

    // Sphinx
    RegexMeasured(CLASS_TAG, """(^|/)docs?/_?(build|themes?|templates?|static)/"""),

    // django
    RegexMeasured(CLASS_TAG, """(^|/)admin_media/"""),
    RegexMeasured(CLASS_TAG, """(^|/)env/"""),

    // Fabric
    RegexMeasured(CLASS_TAG, """^fabfile\.py$"""),

    // WAF
    RegexMeasured(CLASS_TAG, """^waf$"""),

    // .osx
    RegexMeasured(CLASS_TAG, """^.osx$"""),

    // Obj-C

    // Xcode
    RegexMeasured(CLASS_TAG, """\.xctemplate/"""),
    RegexMeasured(CLASS_TAG, """\.imageset/"""),
    RegexMeasured(CLASS_TAG, """\.xc.*/"""),
    RegexMeasured(CLASS_TAG, """(^|/)Info\.plist$"""),
    RegexMeasured(CLASS_TAG, """\.storyboard$"""),

    // Carthage
    RegexMeasured(CLASS_TAG, """(^|/)Carthage/"""),

    // Sparkle
    RegexMeasured(CLASS_TAG, """(^|/)Sparkle/"""),

    // Crashlytics
    RegexMeasured(CLASS_TAG, """Crashlytics.framework/"""),

    // Fabric
    RegexMeasured(CLASS_TAG, """Fabric.framework/"""),

    // BuddyBuild
    RegexMeasured(CLASS_TAG, """BuddyBuildSDK.framework/"""),

    // Realm
    RegexMeasured(CLASS_TAG, """Realm.framework"""),

    // RealmSwift
    RegexMeasured(CLASS_TAG, """RealmSwift.framework"""),

    // git config files
    RegexMeasured(CLASS_TAG, """gitattributes$"""),
    RegexMeasured(CLASS_TAG, """gitignore$"""),
    RegexMeasured(CLASS_TAG, """gitmodules$"""),

    // Groovy

    // Gradle
    RegexMeasured(CLASS_TAG, """(^|/)gradlew$"""),
    RegexMeasured(CLASS_TAG, """(^|/)gradlew\.bat$"""),
    RegexMeasured(CLASS_TAG, """(^|/)gradle/wrapper/"""),

    // Java

    // Maven
    RegexMeasured(CLASS_TAG, """(^|/)mvnw$"""),
    RegexMeasured(CLASS_TAG, """(^|/)mvnw\.cmd$"""),
    RegexMeasured(CLASS_TAG, """(^|/)\.mvn/wrapper/"""),

    // .NET

    // Visual Studio IntelliSense
    RegexMeasured(CLASS_TAG, """-vsdoc\.js$"""),
    RegexMeasured(CLASS_TAG, """\.intellisense\.js$"""),

    // jQuery validation plugin (MS bundles this with asp.net mvc),
    RegexMeasured(CLASS_TAG, """(^|/)jquery([^.]*)\.validate(\.unobtrusive)?\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)jquery([^.]*)\.unobtrusive\-ajax\.js$"""),

    // Microsoft Ajax
    RegexMeasured(CLASS_TAG, """(^|/)[Mm]icrosoft([Mm]vc)?([Aa]jax|[Vv]alidation)(\.debug)?\.js$"""),

    // NuGet
    RegexMeasured(CLASS_TAG, """^[Pp]ackages\/.+\.\d+\/"""),

    // ExtJS
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.*?\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.*?\.xml$"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.*?\.txt$"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.*?\.html$"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.*?\.properties$"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/.sencha/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/docs/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/builds/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/cmd/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/examples/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/locale/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/packages/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/plugins/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/resources/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/src/"""),
    RegexMeasured(CLASS_TAG, """(^|/)extjs/welcome/"""),

    // Html5shiv
    RegexMeasured(CLASS_TAG, """(^|/)html5shiv\.js$"""),

    // Test fixtures
    RegexMeasured(CLASS_TAG, """^[Tt]ests?/fixtures/"""),
    RegexMeasured(CLASS_TAG, """^[Ss]pecs?/fixtures/"""),

    // PhoneGap/Cordova
    RegexMeasured(CLASS_TAG, """(^|/)cordova([^.]*)\.js$"""),
    RegexMeasured(CLASS_TAG, """(^|/)cordova\-\d\.\d(\.\d)?\.js$"""),

    // Foundation js
    RegexMeasured(CLASS_TAG, """foundation(\..*)?\.js$"""),

    // Vagrant
    RegexMeasured(CLASS_TAG, """^Vagrantfile$"""),

    // .DS_Stores
    RegexMeasured(CLASS_TAG, """.[Dd][Ss]_[Ss]tore$"""),

    // R packages
    RegexMeasured(CLASS_TAG, """^vignettes/"""),
    RegexMeasured(CLASS_TAG, """^inst/extdata/"""),

    // Octicons
    RegexMeasured(CLASS_TAG, """octicons.css"""),
    RegexMeasured(CLASS_TAG, """sprockets-octicons.scss"""),

    // Typesafe Activator
    RegexMeasured(CLASS_TAG, """(^|/)activator$"""),
    RegexMeasured(CLASS_TAG, """(^|/)activator\.bat$"""),

    // ProGuard
    RegexMeasured(CLASS_TAG, """proguard.pro"""),
    RegexMeasured(CLASS_TAG, """proguard-rules.pro"""),

    // PuPHPet
    RegexMeasured(CLASS_TAG, """^puphpet/"""),

    // Android Google APIs
    RegexMeasured(CLASS_TAG, """(^|/)\.google_apis/"""),

    // Jenkins Pipeline
    RegexMeasured(CLASS_TAG, """^Jenkinsfile$"""),

    // generated by BUCKLESCRIPT
    RegexMeasured(CLASS_TAG, """\.bs\.js$""")
)
